export const postsDummyData = [
  {
    id: 0,
    artists: "@blondeDude",
    description: "super kick-ass guitar solo",
    status: "OPEN",
    votes: 7,
    videoUrl: "https://static.videezy.com/system/resources/previews/000/000/241/original/guitar-close.mp4",
    category: "",
  },
  {
    id: 1,
    artists: "@blondeDude",
    description: "open organ playing",
    status: "OPEN",
    votes: 7,
    videoUrl: "https://cdn.videvo.net/videvo_files/video/premium/video0298/large_watermarked/601-1_601-0617_preview.mp4",
    category: "",
  },
  {
    id: 2,
    artists: "@blondeDude",
    description: "super kick-ass guitar solo",
    status: "OPEN",
    votes: 7,
    videoUrl: "https://joy.videvo.net/videvo_files/video/free/2017-10/large_watermarked/170609_F_Varanasi_060_preview.mp4",
    category: "",
  },
  {
    id: 3,
    artists: "@blondeDude",
    description: "super kick-ass guitar solo",
    status: "OPEN",
    votes: 7,
    videoUrl: "https://static.videezy.com/system/resources/previews/000/000/241/original/guitar-close.mp4",
    category: "",
  },
  {
    id: 4,
    artists: "@blondeDude",
    description: "super kick-ass guitar solo",
    status: "OPEN",
    votes: 7,
    videoUrl: "https://static.videezy.com/system/resources/previews/000/000/241/original/guitar-close.mp4",
    category: "",
  },
  {
    id: 5,
    artists: "@blondeDude",
    description: "super kick-ass guitar solo",
    status: "OPEN",
    votes: 7,
    videoUrl: "https://static.videezy.com/system/resources/previews/000/000/241/original/guitar-close.mp4",
    category: "",
  },
  {
    id: 6,
    artists: "@blondeDude",
    description: "super kick-ass guitar solo",
    status: "OPEN",
    votes: 7,
    videoUrl: "https://static.videezy.com/system/resources/previews/000/000/241/original/guitar-close.mp4",
    category: "",
  },
  {
    id: 7,
    artists: "@blondeDude",
    description: "super kick-ass guitar solo",
    status: "OPEN",
    votes: 7,
    videoUrl: "https://static.videezy.com/system/resources/previews/000/000/241/original/guitar-close.mp4",
    category: "",
  },
  {
    id: 8,
    artists: "@blondeDude",
    description: "super kick-ass guitar solo",
    status: "OPEN",
    votes: 7,
    videoUrl: "https://static.videezy.com/system/resources/previews/000/000/241/original/guitar-close.mp4",
    category: "",
  },
  {
    id: 9,
    artists: "@blondeDude",
    description: "super kick-ass guitar solo",
    status: "OPEN",
    votes: 7,
    videoUrl: "https://static.videezy.com/system/resources/previews/000/000/241/original/guitar-close.mp4",
    category: "",
  },
];
